### ISSUE TITLE
Feature requests: Pretty charts and off-set support

### ISSUE THREAD

**Issue by DrJohnT** [ianByrne/HASS-ukho_tides#1]
Thank you so much for spending your own time writing this extension for HA.  Having tried a few "tide" extensions for HA, this is the only one that works for me!  

I originally started using an Australian site for tidal information called Willy Weather.  They provide excellent graphics, but can only be integrated into HA by adding a dedicate tab panel mode as shown below: 

![Home Assistant Willy Weather](https://user-images.githubusercontent.com/10464775/111077325-39af4900-84e8-11eb-9711-f46ee36086f0.png)

Later I found they got their tidal data from UKHO.  Indeed their [web site](https://www.willyweather.co.uk/se/greater-london/isle-of-dogs.html) is very informative as it tells me how they derived the tide times from a nearby tide station. i.e. 

![WillyWeather](https://user-images.githubusercontent.com/10464775/111077516-06b98500-84e9-11eb-8e9e-000d14d7653a.png)

I was wondering if your component could possibly be extended to add an off-set for low and high tide, just like Willy Weather apply.

I saw you have an ambition to "Generate pretty charts for the dashboard".  Well I have started using [Apex Charts from HACS](https://github.com/RomRider/apexcharts-card) and I was wondering if your component could possibly be extended to provide the raw data for [Apex Charts](https://github.com/RomRider/apexcharts-card) to use??

FYI, I made a new sensor wrapper around the sensor generated by your component so I could use a button card to encapsulate the information: 

![Home Assistant Dashboard](https://user-images.githubusercontent.com/10464775/111077204-93fbda00-84e7-11eb-94c6-611ef0c9995b.png)

```yaml
sensor:
- platform: template
  sensors:
    greenwich_tide:
      friendly_name_template: >-
        {{ states("sensor.north_woolwich_tide") }} Tide
      value_template: >-
        {% if states("sensor.north_woolwich_tide") == 'Falling' %}
          Low in {{ state_attr("sensor.north_woolwich_tide","next_tide_in") }}
        {% else %}
          High in {{ state_attr("sensor.north_woolwich_tide","next_tide_in") }}
        {% endif %}
      icon_template: >-
        {{ state_attr("sensor.north_woolwich_tide","icon") }}
```

Note that I edited your sensors.py to add the next_tide_in attribute.

Thanks again for the hard work!
