### ISSUE TITLE
Display tide predictions in an easier to read format

### ISSUE THREAD

**Issue by ianByrne** [ianByrne/HASS-ukho_tides#19]
Currently the tide sensor has a `predictions` attribute which is made up of an [array of arrays](https://github.com/ianByrne/HASS-ukho_tides/blob/6e8606768fa638b7ad0f7bbca4bfe083b8cf978a/custom_components/ukho_tides/sensor.py#L166C13-L166C48):

```yaml
predictions: [ [ '2023-01-01 06:00:00', '1.6' ], [ '2023-01-01 13:00:00', '0.2' ] ]
```

Perhaps it can be refactored into something more meaningful, like an array of objects:

```yaml
predictions:
  - datetime: 2023-01-01 06:00:00
    height: 1.6
    event: high tide
  - datetime: 2023-01-01 13:00:00
    height: 0.2
    event: low tide
```

Either refactored (causing breaking changes for anyone using the attribute), or as a new attribute for backwards compatibility.

As requested [here](https://community.home-assistant.io/t/british-hydrographic-office-tidal-information/90197/11). PRs welcome
