### ISSUE TITLE
Not an Issue: questions ;)

### ISSUE THREAD

**Issue by chsims1** [ianByrne/HASS-ukho_tides#3]
Thank you very much for the great integration. I'm a HA novice, and finding it challenging to get at details, since I think the documentation is very much designed as a reference to those who are already familar with it.

I an add the simple sensor to a card fine with station id/name and state of the tide (rising/falling), but how do I access attributes such as tide times & heights?  I did skim through the files very quickly but attribute names didn't spring out at me.

Also, what are high & low tide offsets?

**Comment by chsims1** [comment]
I can now see 'attribution', 'predictions', 'next_high_tide_in', 'next_high_tide_height' etc. for the entity in the HA UI in 'Developer Tools/STATES', but can't see how to work them in to my sensor.yaml, or editing the code from the UI of an 'entities' card  Also, is high tide time supported, or is it a case of calculating it from 'next_high_tide_in'?

Sorry for what I'm sure are very basic questions more concerned with HA syntax, than your integration in particular.

**Comment by ianByrne** [comment]
Hello, and thanks for your questions!

The offsets are an amount in minutes to offset the high/low tide times. The use case would be if you didn't live particularly close to a station, you could tweak the sensor to say something like "my local tide is generally at its highest 10mins before station X predicts it".

As you've found, the 'attributes' of a sensor are the extra properties that are being read from the sensor. In this case, these include things like "Next high/low tide in" and "Next high/low tide height". If you wish to display one of these attributes in your dashboard, you can use the "Entity" card which lets you drill down into these attributes:

![image](https://user-images.githubusercontent.com/1918098/130362161-f76cad5a-d630-457a-918c-2669efd507ce.png)

![image](https://user-images.githubusercontent.com/1918098/130362227-6c8e873b-3535-4028-bdd9-219a556d7a96.png)

For more advanced things [such as templating](https://www.home-assistant.io/docs/configuration/templating/), you can get the attributes using the `states` function, eg:

```
states('sensor.hammersmith_bridge_tide', 'next_high_tide_in')
```

There isn't currently a good way to extract the timestamp of the next high/low tide. You could indeed try to calculate it from the next_high_tide_in value, but it would not be very accurate. An example of how you could do that with templating would be the following:

```yaml
sensor:
  - platform: template
    sensors:
      next_high_tide_time:
        friendly_name: "Next High Tide Time"
        value_template: >
          {% set next_high_tide = {
            "hours": state_attr("sensor.hammersmith_bridge_tide", "next_high_tide_in").split(" ")[0][:-1] | int,
            "minutes": state_attr("sensor.hammersmith_bridge_tide", "next_high_tide_in").split(" ")[1][:-1] | int
          } %}
          {{ now() + timedelta(hours=next_high_tide.hours, minutes=next_high_tide.minutes) }}
        icon_template: mdi:calendar-clock
```

But yeah, I would not recommend this approach - it's quite hacky and as mentioned, would not be very accurate due to the way HASS refreshes the sensor data, etc. We should be able to add the timestamps as additional attributes easy enough - I can see if I get time to take a crack at it in the next few days
